#!/usr/bin/python
import optparse
import os
import sha
import sys
import time
import ConfigParser
from pushr import api, contentmatch

parser = optparse.OptionParser(usage="%prog [OPTS] FILE..")
parser.add_option('--title',
                  action='store')
parser.add_option('--tags',
                  action='store')
options, args = parser.parse_args()

if not args:
    parser.error("need files to upload")

CONFIG_PATH = os.path.expanduser('~/.pushr.conf')
cfg = ConfigParser.RawConfigParser()
try:
    f = file(CONFIG_PATH)
except IOError, e:
    parser.error('cannot open config file: %s' % e)
try:
    cfg.readfp(f)
finally:
    f.close()

try:
    api_key = cfg.get('flickr', 'api-key')
    shared_secret = cfg.get('flickr', 'shared-secret')
    token = cfg.get('flickr', 'token')
except (ConfigParser.NoSectionError,
        ConfigParser.NoOptionError), e:
    parser.error('config incomplete: %s' % e)

api = api.FlickrAPI(
    api_key=api_key,
    shared_secret=shared_secret,
    )

tickets = {}

for filename in args:
    f = file(filename, 'rb')
    try:
        print 'Uploading %s' % filename
        ticket = api.upload(fp=f,
                            auth_token=token,
                            title=options.title,
                            tags=options.tags,
                            )
        print '.. ticket %s' % ticket
        tickets[ticket] = filename
    finally:
        f.close()

matcher = contentmatch.ContentMatch(filename='images.flickr.sha1')
while tickets:
    print 'Polling for status..'
    for status in api.checkTickets(*tickets.keys()):
        ticket_id, photo_id = status
        path = tickets[ticket_id]
        if photo_id is None:
            print 'Upload failed: %s' % path
        else:
            print 'Upload complete: %s -> %s' % (path, photo_id)
            f = file(path)
            try:
                s = sha.new()
                while True:
                    data = f.read(32768)
                    if not data:
                        break
                    s.update(data)
            finally:
                f.close()

            matcher.add(photo_id=photo_id,
                        sha1sum=s.hexdigest())
            matcher.flush()
            print 'SHA-1 added.'
        del tickets[ticket_id]

    if tickets:
        time.sleep(1)

matcher.commit()
print 'Done.'
