#!/usr/bin/python
import errno
import itertools
import os
import sha
import sys
import urllib

FILENAME = 'images.flickr.sha1'

known_photos = set()

f = file(FILENAME)
try:
    for line in f:
        line = line.strip('\n')
        photo_id, sha1sum = line.split(None, 1)
        known_photos.add(sha1sum)
finally:
    f.close()

for topdir in sys.argv[1:]:
    for dirpath, dirnames, filenames in os.walk(topdir):
        filenames[:] = [x for x in filenames if x.endswith('.jpg')]
        for filename in filenames:
            path = os.path.join(dirpath, filename)
            f = file(path)
            try:
                s = sha.new()
                while True:
                    data = f.read(32768)
                    if not data:
                        break
                    s.update(data)
                if s.hexdigest() not in known_photos:
                    print path
            finally:
                f.close()
